name-template: 'v$RESOLVED_VERSION ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - '*.svg'
  - label: 'bug'
    branch:
      - '/bugfix\/.+/'
    title:
      - '/feature\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - 'feature|add(ed)?.+'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ```
        _____           _        __     __             _ 
       / ____|         | |       \ \   / /            | |
      | (___   ___ __ _| | __ _   \ \_/ /_ _ _ __ ___ | |
       \___ \ / __/ _` | |/ _` |   \   / _` | '_ ` _ \| |
       ____) | (_| (_| | | (_| |    | | (_| | | | | | | |
      |_____/ \___\__,_|_|\__,_|    |_|\__,_|_| |_| |_|_|

                        WHAT'S NEW
  ```
  $CHANGES
