name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  scalafmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - run: sbt scalafmtCheckAll

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ['jvm', 'js', 'native']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: JVM tests
        if: matrix.platform == 'jvm'
        run: sbt +core/test
      - name: JS tests
        if: matrix.platform == 'js'
        run: sbt +coreJS/test
      - name: Native tests
        if: matrix.platform == 'native'
        run: sbt +coreNative/test

  publish:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Create docs directory
        run: mkdir generated-docs
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  documentation:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Create docs directory
        run: mkdir generated-docs
      - name: Generate Website
        run: sbt doc
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: generated-docs/
          publish_branch: gh-pages
